# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 06:39
from __future__ import unicode_literals

from django.db import migrations
import partial_index


class Migration(migrations.Migration):

    dependencies = [
        ('enumeration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='counter',
            index=partial_index.PartialIndex(fields=['sequence_id'], name='enumeration_sequenc_dd009b_partial', unique=True, where='period IS NULL', where_postgresql='', where_sqlite=''),
        ),
    ]
