# Generated by Django 4.2.17 on 2024-12-09 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enumeration", "0002_alter_counter_id_alter_gap_id_alter_sequence_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("position", models.PositiveIntegerField(null=True)),
                ("date", models.DateField()),
                (
                    "counter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="enumeration.counter",
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="enumeration.sequence",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
